name: Auto-Signed Commit from Actions

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sign-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Git identity (required to commit)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Modify file
        run: echo "Update on $(date)" >> test.txt

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add test.txt
          git commit -m "Automated commit from GitHub Actions"
          git push
