name: Auto-Signed Commit from Actions

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sign-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Modify file
        run: echo "Update on $(date)" >> test.txt

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add test.txt
          git commit -m "Automated commit from GitHub Actions"
          git push
